import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Nav from "./components/nav/Nav";
import { NavLateral } from "./components/nav/NavLaterarl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MonyFix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <NavLateral />
      <Nav/>

      {/* main wrapper: use CSS variable set by NavLateral to push content when sidebar expands */}
      <div
        style={{
          paddingLeft: 'var(--sidebar-width, 5rem)',
          transition: 'padding-left 300ms ease-in-out',
        }}
        className="pt-20 min-h-screen bg-[#EFF0F6]"
      >
        {children}
      </div>
       </body>
     </html>
   );
 }
